package org.bouncycastle.asn1.pkcs;

import com.tencent.connect.common.Constants;
import io.dcloud.feature.contacts.JsContactsMgr;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* JADX INFO: loaded from: classes3.dex */
public interface PKCSObjectIdentifiers {
    public static final ASN1ObjectIdentifier RC2_CBC;
    public static final ASN1ObjectIdentifier bagtypes;
    public static final ASN1ObjectIdentifier canNotDecryptAny;
    public static final ASN1ObjectIdentifier certBag;
    public static final ASN1ObjectIdentifier certTypes;
    public static final ASN1ObjectIdentifier crlBag;
    public static final ASN1ObjectIdentifier crlTypes;
    public static final ASN1ObjectIdentifier data;
    public static final ASN1ObjectIdentifier des_EDE3_CBC;
    public static final ASN1ObjectIdentifier dhKeyAgreement;
    public static final ASN1ObjectIdentifier digestAlgorithm;
    public static final ASN1ObjectIdentifier digestedData;
    public static final ASN1ObjectIdentifier encryptedData;
    public static final ASN1ObjectIdentifier encryptionAlgorithm;
    public static final ASN1ObjectIdentifier envelopedData;
    public static final ASN1ObjectIdentifier id_PBES2;
    public static final ASN1ObjectIdentifier id_PBKDF2;
    public static final ASN1ObjectIdentifier id_RSAES_OAEP;
    public static final ASN1ObjectIdentifier id_RSASSA_PSS;
    public static final ASN1ObjectIdentifier id_aa;
    public static final ASN1ObjectIdentifier id_aa_asymmDecryptKeyID;
    public static final ASN1ObjectIdentifier id_aa_cmsAlgorithmProtect;
    public static final ASN1ObjectIdentifier id_aa_commitmentType;
    public static final ASN1ObjectIdentifier id_aa_communityIdentifiers;
    public static final ASN1ObjectIdentifier id_aa_contentHint;
    public static final ASN1ObjectIdentifier id_aa_contentIdentifier;
    public static final ASN1ObjectIdentifier id_aa_contentReference;
    public static final ASN1ObjectIdentifier id_aa_decryptKeyID;
    public static final ASN1ObjectIdentifier id_aa_encrypKeyPref;
    public static final ASN1ObjectIdentifier id_aa_ets_archiveTimestamp;
    public static final ASN1ObjectIdentifier id_aa_ets_certCRLTimestamp;
    public static final ASN1ObjectIdentifier id_aa_ets_certValues;
    public static final ASN1ObjectIdentifier id_aa_ets_certificateRefs;
    public static final ASN1ObjectIdentifier id_aa_ets_commitmentType;
    public static final ASN1ObjectIdentifier id_aa_ets_contentTimestamp;
    public static final ASN1ObjectIdentifier id_aa_ets_escTimeStamp;
    public static final ASN1ObjectIdentifier id_aa_ets_otherSigCert;
    public static final ASN1ObjectIdentifier id_aa_ets_revocationRefs;
    public static final ASN1ObjectIdentifier id_aa_ets_revocationValues;
    public static final ASN1ObjectIdentifier id_aa_ets_sigPolicyId;
    public static final ASN1ObjectIdentifier id_aa_ets_signerAttr;
    public static final ASN1ObjectIdentifier id_aa_ets_signerLocation;
    public static final ASN1ObjectIdentifier id_aa_implCompressAlgs;
    public static final ASN1ObjectIdentifier id_aa_implCryptoAlgs;
    public static final ASN1ObjectIdentifier id_aa_msgSigDigest;
    public static final ASN1ObjectIdentifier id_aa_otherSigCert;
    public static final ASN1ObjectIdentifier id_aa_receiptRequest;
    public static final ASN1ObjectIdentifier id_aa_sigPolicyId;
    public static final ASN1ObjectIdentifier id_aa_signatureTimeStampToken;
    public static final ASN1ObjectIdentifier id_aa_signerLocation;
    public static final ASN1ObjectIdentifier id_aa_signingCertificate;
    public static final ASN1ObjectIdentifier id_aa_signingCertificateV2;
    public static final ASN1ObjectIdentifier id_alg;
    public static final ASN1ObjectIdentifier id_alg_AEADChaCha20Poly1305;
    public static final ASN1ObjectIdentifier id_alg_CMS3DESwrap;
    public static final ASN1ObjectIdentifier id_alg_CMSRC2wrap;
    public static final ASN1ObjectIdentifier id_alg_ESDH;
    public static final ASN1ObjectIdentifier id_alg_PWRI_KEK;
    public static final ASN1ObjectIdentifier id_alg_SSDH;
    public static final ASN1ObjectIdentifier id_alg_hss_lms_hashsig;
    public static final ASN1ObjectIdentifier id_ct;
    public static final ASN1ObjectIdentifier id_ct_TSTInfo;
    public static final ASN1ObjectIdentifier id_ct_authData;
    public static final ASN1ObjectIdentifier id_ct_authEnvelopedData;
    public static final ASN1ObjectIdentifier id_ct_compressedData;
    public static final ASN1ObjectIdentifier id_ct_timestampedData;
    public static final ASN1ObjectIdentifier id_cti;
    public static final ASN1ObjectIdentifier id_cti_ets_proofOfApproval;
    public static final ASN1ObjectIdentifier id_cti_ets_proofOfCreation;
    public static final ASN1ObjectIdentifier id_cti_ets_proofOfDelivery;
    public static final ASN1ObjectIdentifier id_cti_ets_proofOfOrigin;
    public static final ASN1ObjectIdentifier id_cti_ets_proofOfReceipt;
    public static final ASN1ObjectIdentifier id_cti_ets_proofOfSender;
    public static final ASN1ObjectIdentifier id_hmacWithSHA1;
    public static final ASN1ObjectIdentifier id_hmacWithSHA224;
    public static final ASN1ObjectIdentifier id_hmacWithSHA256;
    public static final ASN1ObjectIdentifier id_hmacWithSHA384;
    public static final ASN1ObjectIdentifier id_hmacWithSHA512;
    public static final ASN1ObjectIdentifier id_mgf1;
    public static final ASN1ObjectIdentifier id_pSpecified;
    public static final ASN1ObjectIdentifier id_rsa_KEM;
    public static final ASN1ObjectIdentifier id_smime;
    public static final String id_spq = "1.2.840.113549.1.9.16.5";
    public static final ASN1ObjectIdentifier id_spq_ets_unotice;
    public static final ASN1ObjectIdentifier id_spq_ets_uri;
    public static final ASN1ObjectIdentifier keyBag;
    public static final ASN1ObjectIdentifier md2;
    public static final ASN1ObjectIdentifier md2WithRSAEncryption;
    public static final ASN1ObjectIdentifier md4;
    public static final ASN1ObjectIdentifier md4WithRSAEncryption;
    public static final ASN1ObjectIdentifier md5;
    public static final ASN1ObjectIdentifier md5WithRSAEncryption;
    public static final ASN1ObjectIdentifier pbeWithMD2AndDES_CBC;
    public static final ASN1ObjectIdentifier pbeWithMD2AndRC2_CBC;
    public static final ASN1ObjectIdentifier pbeWithMD5AndDES_CBC;
    public static final ASN1ObjectIdentifier pbeWithMD5AndRC2_CBC;
    public static final ASN1ObjectIdentifier pbeWithSHA1AndDES_CBC;
    public static final ASN1ObjectIdentifier pbeWithSHA1AndRC2_CBC;
    public static final ASN1ObjectIdentifier pbeWithSHAAnd128BitRC2_CBC;
    public static final ASN1ObjectIdentifier pbeWithSHAAnd128BitRC4;
    public static final ASN1ObjectIdentifier pbeWithSHAAnd2_KeyTripleDES_CBC;
    public static final ASN1ObjectIdentifier pbeWithSHAAnd3_KeyTripleDES_CBC;
    public static final ASN1ObjectIdentifier pbeWithSHAAnd40BitRC2_CBC;
    public static final ASN1ObjectIdentifier pbeWithSHAAnd40BitRC4;
    public static final ASN1ObjectIdentifier pbewithSHAAnd40BitRC2_CBC;
    public static final ASN1ObjectIdentifier pkcs8ShroudedKeyBag;
    public static final ASN1ObjectIdentifier pkcs_1;
    public static final ASN1ObjectIdentifier pkcs_12;
    public static final ASN1ObjectIdentifier pkcs_12PbeIds;
    public static final ASN1ObjectIdentifier pkcs_3;
    public static final ASN1ObjectIdentifier pkcs_5;
    public static final ASN1ObjectIdentifier pkcs_7;
    public static final ASN1ObjectIdentifier pkcs_9;
    public static final ASN1ObjectIdentifier pkcs_9_at_challengePassword;
    public static final ASN1ObjectIdentifier pkcs_9_at_contentType;
    public static final ASN1ObjectIdentifier pkcs_9_at_counterSignature;
    public static final ASN1ObjectIdentifier pkcs_9_at_emailAddress;
    public static final ASN1ObjectIdentifier pkcs_9_at_extendedCertificateAttributes;
    public static final ASN1ObjectIdentifier pkcs_9_at_extensionRequest;
    public static final ASN1ObjectIdentifier pkcs_9_at_friendlyName;
    public static final ASN1ObjectIdentifier pkcs_9_at_localKeyId;
    public static final ASN1ObjectIdentifier pkcs_9_at_messageDigest;
    public static final ASN1ObjectIdentifier pkcs_9_at_signingDescription;
    public static final ASN1ObjectIdentifier pkcs_9_at_signingTime;
    public static final ASN1ObjectIdentifier pkcs_9_at_smimeCapabilities;
    public static final ASN1ObjectIdentifier pkcs_9_at_unstructuredAddress;
    public static final ASN1ObjectIdentifier pkcs_9_at_unstructuredName;
    public static final ASN1ObjectIdentifier preferSignedData;
    public static final ASN1ObjectIdentifier rc4;
    public static final ASN1ObjectIdentifier rsaEncryption;
    public static final ASN1ObjectIdentifier sMIMECapabilitiesVersions;
    public static final ASN1ObjectIdentifier safeContentsBag;
    public static final ASN1ObjectIdentifier sdsiCertificate;
    public static final ASN1ObjectIdentifier secretBag;
    public static final ASN1ObjectIdentifier sha1WithRSAEncryption;
    public static final ASN1ObjectIdentifier sha224WithRSAEncryption;
    public static final ASN1ObjectIdentifier sha256WithRSAEncryption;
    public static final ASN1ObjectIdentifier sha384WithRSAEncryption;
    public static final ASN1ObjectIdentifier sha512WithRSAEncryption;
    public static final ASN1ObjectIdentifier sha512_224WithRSAEncryption;
    public static final ASN1ObjectIdentifier sha512_256WithRSAEncryption;
    public static final ASN1ObjectIdentifier signedAndEnvelopedData;
    public static final ASN1ObjectIdentifier signedData;
    public static final ASN1ObjectIdentifier srsaOAEPEncryptionSET;
    public static final ASN1ObjectIdentifier x509Certificate;
    public static final ASN1ObjectIdentifier x509Crl;
    public static final ASN1ObjectIdentifier x509certType;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.840.113549.1.1");
        pkcs_1 = aSN1ObjectIdentifier;
        rsaEncryption = aSN1ObjectIdentifier.branch("1");
        md2WithRSAEncryption = pkcs_1.branch("2");
        md4WithRSAEncryption = pkcs_1.branch("3");
        md5WithRSAEncryption = pkcs_1.branch("4");
        sha1WithRSAEncryption = pkcs_1.branch("5");
        srsaOAEPEncryptionSET = pkcs_1.branch(Constants.VIA_SHARE_TYPE_INFO);
        id_RSAES_OAEP = pkcs_1.branch("7");
        id_mgf1 = pkcs_1.branch(Constants.VIA_SHARE_TYPE_PUBLISHVIDEO);
        id_pSpecified = pkcs_1.branch(Constants.VIA_SHARE_TYPE_MINI_PROGRAM);
        id_RSASSA_PSS = pkcs_1.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_QQ);
        sha256WithRSAEncryption = pkcs_1.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_QZONE);
        sha384WithRSAEncryption = pkcs_1.branch(Constants.VIA_REPORT_TYPE_SET_AVATAR);
        sha512WithRSAEncryption = pkcs_1.branch("13");
        sha224WithRSAEncryption = pkcs_1.branch(Constants.VIA_REPORT_TYPE_MAKE_FRIEND);
        sha512_224WithRSAEncryption = pkcs_1.branch(Constants.VIA_REPORT_TYPE_WPA_STATE);
        sha512_256WithRSAEncryption = pkcs_1.branch(Constants.VIA_REPORT_TYPE_START_WAP);
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("1.2.840.113549.1.3");
        pkcs_3 = aSN1ObjectIdentifier2;
        dhKeyAgreement = aSN1ObjectIdentifier2.branch("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier("1.2.840.113549.1.5");
        pkcs_5 = aSN1ObjectIdentifier3;
        pbeWithMD2AndDES_CBC = aSN1ObjectIdentifier3.branch("1");
        pbeWithMD2AndRC2_CBC = pkcs_5.branch("4");
        pbeWithMD5AndDES_CBC = pkcs_5.branch("3");
        pbeWithMD5AndRC2_CBC = pkcs_5.branch(Constants.VIA_SHARE_TYPE_INFO);
        pbeWithSHA1AndDES_CBC = pkcs_5.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_QQ);
        pbeWithSHA1AndRC2_CBC = pkcs_5.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_QZONE);
        id_PBES2 = pkcs_5.branch("13");
        id_PBKDF2 = pkcs_5.branch(Constants.VIA_REPORT_TYPE_SET_AVATAR);
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier("1.2.840.113549.3");
        encryptionAlgorithm = aSN1ObjectIdentifier4;
        des_EDE3_CBC = aSN1ObjectIdentifier4.branch("7");
        RC2_CBC = encryptionAlgorithm.branch("2");
        rc4 = encryptionAlgorithm.branch("4");
        ASN1ObjectIdentifier aSN1ObjectIdentifier5 = new ASN1ObjectIdentifier("1.2.840.113549.2");
        digestAlgorithm = aSN1ObjectIdentifier5;
        md2 = aSN1ObjectIdentifier5.branch("2");
        md4 = digestAlgorithm.branch("4");
        md5 = digestAlgorithm.branch("5");
        id_hmacWithSHA1 = digestAlgorithm.branch("7").intern();
        id_hmacWithSHA224 = digestAlgorithm.branch(Constants.VIA_SHARE_TYPE_PUBLISHVIDEO).intern();
        id_hmacWithSHA256 = digestAlgorithm.branch(Constants.VIA_SHARE_TYPE_MINI_PROGRAM).intern();
        id_hmacWithSHA384 = digestAlgorithm.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_QQ).intern();
        id_hmacWithSHA512 = digestAlgorithm.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_QZONE).intern();
        pkcs_7 = new ASN1ObjectIdentifier("1.2.840.113549.1.7").intern();
        data = new ASN1ObjectIdentifier("1.2.840.113549.1.7.1").intern();
        signedData = new ASN1ObjectIdentifier("1.2.840.113549.1.7.2").intern();
        envelopedData = new ASN1ObjectIdentifier("1.2.840.113549.1.7.3").intern();
        signedAndEnvelopedData = new ASN1ObjectIdentifier("1.2.840.113549.1.7.4").intern();
        digestedData = new ASN1ObjectIdentifier("1.2.840.113549.1.7.5").intern();
        encryptedData = new ASN1ObjectIdentifier("1.2.840.113549.1.7.6").intern();
        ASN1ObjectIdentifier aSN1ObjectIdentifier6 = new ASN1ObjectIdentifier("1.2.840.113549.1.9");
        pkcs_9 = aSN1ObjectIdentifier6;
        pkcs_9_at_emailAddress = aSN1ObjectIdentifier6.branch("1").intern();
        pkcs_9_at_unstructuredName = pkcs_9.branch("2").intern();
        pkcs_9_at_contentType = pkcs_9.branch("3").intern();
        pkcs_9_at_messageDigest = pkcs_9.branch("4").intern();
        pkcs_9_at_signingTime = pkcs_9.branch("5").intern();
        pkcs_9_at_counterSignature = pkcs_9.branch(Constants.VIA_SHARE_TYPE_INFO).intern();
        pkcs_9_at_challengePassword = pkcs_9.branch("7").intern();
        pkcs_9_at_unstructuredAddress = pkcs_9.branch(Constants.VIA_SHARE_TYPE_PUBLISHVIDEO).intern();
        pkcs_9_at_extendedCertificateAttributes = pkcs_9.branch(Constants.VIA_SHARE_TYPE_MINI_PROGRAM).intern();
        pkcs_9_at_signingDescription = pkcs_9.branch("13").intern();
        pkcs_9_at_extensionRequest = pkcs_9.branch(Constants.VIA_REPORT_TYPE_MAKE_FRIEND).intern();
        pkcs_9_at_smimeCapabilities = pkcs_9.branch(Constants.VIA_REPORT_TYPE_WPA_STATE).intern();
        id_smime = pkcs_9.branch(Constants.VIA_REPORT_TYPE_START_WAP).intern();
        pkcs_9_at_friendlyName = pkcs_9.branch(JsContactsMgr.PERMISSION_DENIED_ERROR).intern();
        pkcs_9_at_localKeyId = pkcs_9.branch("21").intern();
        x509certType = pkcs_9.branch("22.1");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch = pkcs_9.branch(Constants.VIA_REPORT_TYPE_DATALINE);
        certTypes = aSN1ObjectIdentifierBranch;
        x509Certificate = aSN1ObjectIdentifierBranch.branch("1").intern();
        sdsiCertificate = certTypes.branch("2").intern();
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch2 = pkcs_9.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_TROOPBAR);
        crlTypes = aSN1ObjectIdentifierBranch2;
        x509Crl = aSN1ObjectIdentifierBranch2.branch("1").intern();
        id_aa_cmsAlgorithmProtect = pkcs_9.branch("52").intern();
        preferSignedData = pkcs_9.branch("15.1");
        canNotDecryptAny = pkcs_9.branch("15.2");
        sMIMECapabilitiesVersions = pkcs_9.branch("15.3");
        ASN1ObjectIdentifier aSN1ObjectIdentifier7 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.1");
        id_ct = aSN1ObjectIdentifier7;
        id_ct_authData = aSN1ObjectIdentifier7.branch("2");
        id_ct_TSTInfo = id_ct.branch("4");
        id_ct_compressedData = id_ct.branch(Constants.VIA_SHARE_TYPE_MINI_PROGRAM);
        id_ct_authEnvelopedData = id_ct.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_TROOPBAR);
        id_ct_timestampedData = id_ct.branch("31");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch3 = id_smime.branch("3");
        id_alg = aSN1ObjectIdentifierBranch3;
        id_alg_PWRI_KEK = aSN1ObjectIdentifierBranch3.branch(Constants.VIA_SHARE_TYPE_MINI_PROGRAM);
        id_rsa_KEM = id_alg.branch(Constants.VIA_REPORT_TYPE_MAKE_FRIEND);
        id_alg_hss_lms_hashsig = id_alg.branch(Constants.VIA_REPORT_TYPE_START_GROUP);
        id_alg_AEADChaCha20Poly1305 = id_alg.branch("18");
        ASN1ObjectIdentifier aSN1ObjectIdentifier8 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.6");
        id_cti = aSN1ObjectIdentifier8;
        id_cti_ets_proofOfOrigin = aSN1ObjectIdentifier8.branch("1");
        id_cti_ets_proofOfReceipt = id_cti.branch("2");
        id_cti_ets_proofOfDelivery = id_cti.branch("3");
        id_cti_ets_proofOfSender = id_cti.branch("4");
        id_cti_ets_proofOfApproval = id_cti.branch("5");
        id_cti_ets_proofOfCreation = id_cti.branch(Constants.VIA_SHARE_TYPE_INFO);
        ASN1ObjectIdentifier aSN1ObjectIdentifier9 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.2");
        id_aa = aSN1ObjectIdentifier9;
        id_aa_receiptRequest = aSN1ObjectIdentifier9.branch("1");
        id_aa_contentHint = id_aa.branch("4");
        id_aa_msgSigDigest = id_aa.branch("5");
        id_aa_contentReference = id_aa.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_QQ);
        id_aa_encrypKeyPref = id_aa.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_QZONE);
        id_aa_signingCertificate = id_aa.branch(Constants.VIA_REPORT_TYPE_SET_AVATAR);
        id_aa_signingCertificateV2 = id_aa.branch("47");
        id_aa_contentIdentifier = id_aa.branch("7");
        id_aa_signatureTimeStampToken = id_aa.branch(Constants.VIA_REPORT_TYPE_MAKE_FRIEND);
        id_aa_ets_sigPolicyId = id_aa.branch(Constants.VIA_REPORT_TYPE_WPA_STATE);
        id_aa_ets_commitmentType = id_aa.branch(Constants.VIA_REPORT_TYPE_START_WAP);
        id_aa_ets_signerLocation = id_aa.branch(Constants.VIA_REPORT_TYPE_START_GROUP);
        id_aa_ets_signerAttr = id_aa.branch("18");
        id_aa_ets_otherSigCert = id_aa.branch(Constants.VIA_ACT_TYPE_NINETEEN);
        id_aa_ets_contentTimestamp = id_aa.branch(JsContactsMgr.PERMISSION_DENIED_ERROR);
        id_aa_ets_certificateRefs = id_aa.branch("21");
        id_aa_ets_revocationRefs = id_aa.branch(Constants.VIA_REPORT_TYPE_DATALINE);
        id_aa_ets_certValues = id_aa.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_TROOPBAR);
        id_aa_ets_revocationValues = id_aa.branch(Constants.VIA_REPORT_TYPE_CHAT_AIO);
        id_aa_ets_escTimeStamp = id_aa.branch(Constants.VIA_REPORT_TYPE_CHAT_AUDIO);
        id_aa_ets_certCRLTimestamp = id_aa.branch(Constants.VIA_REPORT_TYPE_CHAT_VIDEO);
        id_aa_ets_archiveTimestamp = id_aa.branch("27");
        id_aa_decryptKeyID = id_aa.branch("37");
        id_aa_implCryptoAlgs = id_aa.branch("38");
        id_aa_asymmDecryptKeyID = id_aa.branch("54");
        id_aa_implCompressAlgs = id_aa.branch("43");
        id_aa_communityIdentifiers = id_aa.branch("40");
        id_aa_sigPolicyId = id_aa_ets_sigPolicyId;
        id_aa_commitmentType = id_aa_ets_commitmentType;
        id_aa_signerLocation = id_aa_ets_signerLocation;
        id_aa_otherSigCert = id_aa_ets_otherSigCert;
        id_spq_ets_uri = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.1");
        id_spq_ets_unotice = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.2");
        ASN1ObjectIdentifier aSN1ObjectIdentifier10 = new ASN1ObjectIdentifier("1.2.840.113549.1.12");
        pkcs_12 = aSN1ObjectIdentifier10;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch4 = aSN1ObjectIdentifier10.branch("10.1");
        bagtypes = aSN1ObjectIdentifierBranch4;
        keyBag = aSN1ObjectIdentifierBranch4.branch("1");
        pkcs8ShroudedKeyBag = bagtypes.branch("2");
        certBag = bagtypes.branch("3");
        crlBag = bagtypes.branch("4");
        secretBag = bagtypes.branch("5");
        safeContentsBag = bagtypes.branch(Constants.VIA_SHARE_TYPE_INFO);
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch5 = pkcs_12.branch("1");
        pkcs_12PbeIds = aSN1ObjectIdentifierBranch5;
        pbeWithSHAAnd128BitRC4 = aSN1ObjectIdentifierBranch5.branch("1");
        pbeWithSHAAnd40BitRC4 = pkcs_12PbeIds.branch("2");
        pbeWithSHAAnd3_KeyTripleDES_CBC = pkcs_12PbeIds.branch("3");
        pbeWithSHAAnd2_KeyTripleDES_CBC = pkcs_12PbeIds.branch("4");
        pbeWithSHAAnd128BitRC2_CBC = pkcs_12PbeIds.branch("5");
        pbeWithSHAAnd40BitRC2_CBC = pkcs_12PbeIds.branch(Constants.VIA_SHARE_TYPE_INFO);
        pbewithSHAAnd40BitRC2_CBC = pkcs_12PbeIds.branch(Constants.VIA_SHARE_TYPE_INFO);
        id_alg_CMS3DESwrap = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.6");
        id_alg_CMSRC2wrap = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.7");
        id_alg_ESDH = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.5");
        id_alg_SSDH = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.10");
    }
}
