package org.bouncycastle.asn1.bc;

import com.tencent.connect.common.Constants;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* JADX INFO: loaded from: classes3.dex */
public interface BCObjectIdentifiers {
    public static final ASN1ObjectIdentifier bc;
    public static final ASN1ObjectIdentifier bc_exch;
    public static final ASN1ObjectIdentifier bc_ext;
    public static final ASN1ObjectIdentifier bc_pbe;
    public static final ASN1ObjectIdentifier bc_pbe_sha1;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12_aes128_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12_aes192_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12_aes256_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs5;
    public static final ASN1ObjectIdentifier bc_pbe_sha224;
    public static final ASN1ObjectIdentifier bc_pbe_sha256;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12_aes128_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12_aes192_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12_aes256_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs5;
    public static final ASN1ObjectIdentifier bc_pbe_sha384;
    public static final ASN1ObjectIdentifier bc_pbe_sha512;
    public static final ASN1ObjectIdentifier bc_sig;
    public static final ASN1ObjectIdentifier linkedCertificate;
    public static final ASN1ObjectIdentifier newHope;
    public static final ASN1ObjectIdentifier qTESLA;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_I;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_III_size;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_III_speed;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_p_I;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_p_III;
    public static final ASN1ObjectIdentifier qTESLA_p_I;
    public static final ASN1ObjectIdentifier qTESLA_p_III;
    public static final ASN1ObjectIdentifier sphincs256;
    public static final ASN1ObjectIdentifier sphincs256_with_BLAKE512;
    public static final ASN1ObjectIdentifier sphincs256_with_SHA3_512;
    public static final ASN1ObjectIdentifier sphincs256_with_SHA512;
    public static final ASN1ObjectIdentifier xmss;
    public static final ASN1ObjectIdentifier xmss_SHA256;
    public static final ASN1ObjectIdentifier xmss_SHA256ph;
    public static final ASN1ObjectIdentifier xmss_SHA512;
    public static final ASN1ObjectIdentifier xmss_SHA512ph;
    public static final ASN1ObjectIdentifier xmss_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_SHAKE128ph;
    public static final ASN1ObjectIdentifier xmss_SHAKE256;
    public static final ASN1ObjectIdentifier xmss_SHAKE256ph;
    public static final ASN1ObjectIdentifier xmss_mt;
    public static final ASN1ObjectIdentifier xmss_mt_SHA256;
    public static final ASN1ObjectIdentifier xmss_mt_SHA256ph;
    public static final ASN1ObjectIdentifier xmss_mt_SHA512;
    public static final ASN1ObjectIdentifier xmss_mt_SHA512ph;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE128ph;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE256;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE256ph;
    public static final ASN1ObjectIdentifier xmss_mt_with_SHA256;
    public static final ASN1ObjectIdentifier xmss_mt_with_SHA512;
    public static final ASN1ObjectIdentifier xmss_mt_with_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_mt_with_SHAKE256;
    public static final ASN1ObjectIdentifier xmss_with_SHA256;
    public static final ASN1ObjectIdentifier xmss_with_SHA512;
    public static final ASN1ObjectIdentifier xmss_with_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_with_SHAKE256;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.3.6.1.4.1.22554");
        bc = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch = aSN1ObjectIdentifier.branch("1");
        bc_pbe = aSN1ObjectIdentifierBranch;
        bc_pbe_sha1 = aSN1ObjectIdentifierBranch.branch("1");
        bc_pbe_sha256 = bc_pbe.branch("2.1");
        bc_pbe_sha384 = bc_pbe.branch("2.2");
        bc_pbe_sha512 = bc_pbe.branch("2.3");
        bc_pbe_sha224 = bc_pbe.branch("2.4");
        bc_pbe_sha1_pkcs5 = bc_pbe_sha1.branch("1");
        bc_pbe_sha1_pkcs12 = bc_pbe_sha1.branch("2");
        bc_pbe_sha256_pkcs5 = bc_pbe_sha256.branch("1");
        bc_pbe_sha256_pkcs12 = bc_pbe_sha256.branch("2");
        bc_pbe_sha1_pkcs12_aes128_cbc = bc_pbe_sha1_pkcs12.branch("1.2");
        bc_pbe_sha1_pkcs12_aes192_cbc = bc_pbe_sha1_pkcs12.branch("1.22");
        bc_pbe_sha1_pkcs12_aes256_cbc = bc_pbe_sha1_pkcs12.branch("1.42");
        bc_pbe_sha256_pkcs12_aes128_cbc = bc_pbe_sha256_pkcs12.branch("1.2");
        bc_pbe_sha256_pkcs12_aes192_cbc = bc_pbe_sha256_pkcs12.branch("1.22");
        bc_pbe_sha256_pkcs12_aes256_cbc = bc_pbe_sha256_pkcs12.branch("1.42");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch2 = bc.branch("2");
        bc_sig = aSN1ObjectIdentifierBranch2;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch3 = aSN1ObjectIdentifierBranch2.branch("1");
        sphincs256 = aSN1ObjectIdentifierBranch3;
        sphincs256_with_BLAKE512 = aSN1ObjectIdentifierBranch3.branch("1");
        sphincs256_with_SHA512 = sphincs256.branch("2");
        sphincs256_with_SHA3_512 = sphincs256.branch("3");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch4 = bc_sig.branch("2");
        xmss = aSN1ObjectIdentifierBranch4;
        xmss_SHA256ph = aSN1ObjectIdentifierBranch4.branch("1");
        xmss_SHA512ph = xmss.branch("2");
        xmss_SHAKE128ph = xmss.branch("3");
        xmss_SHAKE256ph = xmss.branch("4");
        xmss_SHA256 = xmss.branch("5");
        xmss_SHA512 = xmss.branch(Constants.VIA_SHARE_TYPE_INFO);
        xmss_SHAKE128 = xmss.branch("7");
        xmss_SHAKE256 = xmss.branch(Constants.VIA_SHARE_TYPE_PUBLISHVIDEO);
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch5 = bc_sig.branch("3");
        xmss_mt = aSN1ObjectIdentifierBranch5;
        xmss_mt_SHA256ph = aSN1ObjectIdentifierBranch5.branch("1");
        xmss_mt_SHA512ph = xmss_mt.branch("2");
        xmss_mt_SHAKE128ph = xmss_mt.branch("3");
        xmss_mt_SHAKE256ph = xmss_mt.branch("4");
        xmss_mt_SHA256 = xmss_mt.branch("5");
        xmss_mt_SHA512 = xmss_mt.branch(Constants.VIA_SHARE_TYPE_INFO);
        xmss_mt_SHAKE128 = xmss_mt.branch("7");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch6 = xmss_mt.branch(Constants.VIA_SHARE_TYPE_PUBLISHVIDEO);
        xmss_mt_SHAKE256 = aSN1ObjectIdentifierBranch6;
        xmss_with_SHA256 = xmss_SHA256ph;
        xmss_with_SHA512 = xmss_SHA512ph;
        xmss_with_SHAKE128 = xmss_SHAKE128ph;
        xmss_with_SHAKE256 = xmss_SHAKE256ph;
        xmss_mt_with_SHA256 = xmss_mt_SHA256ph;
        xmss_mt_with_SHA512 = xmss_mt_SHA512ph;
        xmss_mt_with_SHAKE128 = xmss_mt_SHAKE128;
        xmss_mt_with_SHAKE256 = aSN1ObjectIdentifierBranch6;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch7 = bc_sig.branch("4");
        qTESLA = aSN1ObjectIdentifierBranch7;
        qTESLA_Rnd1_I = aSN1ObjectIdentifierBranch7.branch("1");
        qTESLA_Rnd1_III_size = qTESLA.branch("2");
        qTESLA_Rnd1_III_speed = qTESLA.branch("3");
        qTESLA_Rnd1_p_I = qTESLA.branch("4");
        qTESLA_Rnd1_p_III = qTESLA.branch("5");
        qTESLA_p_I = qTESLA.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_QZONE);
        qTESLA_p_III = qTESLA.branch(Constants.VIA_REPORT_TYPE_SET_AVATAR);
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch8 = bc.branch("3");
        bc_exch = aSN1ObjectIdentifierBranch8;
        newHope = aSN1ObjectIdentifierBranch8.branch("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch9 = bc.branch("4");
        bc_ext = aSN1ObjectIdentifierBranch9;
        linkedCertificate = aSN1ObjectIdentifierBranch9.branch("1");
    }
}
