package org.bouncycastle.asn1.nist;

import com.tencent.connect.common.Constants;
import io.dcloud.feature.contacts.JsContactsMgr;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* JADX INFO: loaded from: classes3.dex */
public interface NISTObjectIdentifiers {
    public static final ASN1ObjectIdentifier aes;
    public static final ASN1ObjectIdentifier dsa_with_sha224;
    public static final ASN1ObjectIdentifier dsa_with_sha256;
    public static final ASN1ObjectIdentifier dsa_with_sha384;
    public static final ASN1ObjectIdentifier dsa_with_sha512;
    public static final ASN1ObjectIdentifier hashAlgs;
    public static final ASN1ObjectIdentifier id_KmacWithSHAKE128;
    public static final ASN1ObjectIdentifier id_KmacWithSHAKE256;
    public static final ASN1ObjectIdentifier id_aes128_CBC;
    public static final ASN1ObjectIdentifier id_aes128_CCM;
    public static final ASN1ObjectIdentifier id_aes128_CFB;
    public static final ASN1ObjectIdentifier id_aes128_ECB;
    public static final ASN1ObjectIdentifier id_aes128_GCM;
    public static final ASN1ObjectIdentifier id_aes128_OFB;
    public static final ASN1ObjectIdentifier id_aes128_wrap;
    public static final ASN1ObjectIdentifier id_aes128_wrap_pad;
    public static final ASN1ObjectIdentifier id_aes192_CBC;
    public static final ASN1ObjectIdentifier id_aes192_CCM;
    public static final ASN1ObjectIdentifier id_aes192_CFB;
    public static final ASN1ObjectIdentifier id_aes192_ECB;
    public static final ASN1ObjectIdentifier id_aes192_GCM;
    public static final ASN1ObjectIdentifier id_aes192_OFB;
    public static final ASN1ObjectIdentifier id_aes192_wrap;
    public static final ASN1ObjectIdentifier id_aes192_wrap_pad;
    public static final ASN1ObjectIdentifier id_aes256_CBC;
    public static final ASN1ObjectIdentifier id_aes256_CCM;
    public static final ASN1ObjectIdentifier id_aes256_CFB;
    public static final ASN1ObjectIdentifier id_aes256_ECB;
    public static final ASN1ObjectIdentifier id_aes256_GCM;
    public static final ASN1ObjectIdentifier id_aes256_OFB;
    public static final ASN1ObjectIdentifier id_aes256_wrap;
    public static final ASN1ObjectIdentifier id_aes256_wrap_pad;
    public static final ASN1ObjectIdentifier id_dsa_with_sha2;
    public static final ASN1ObjectIdentifier id_dsa_with_sha3_224;
    public static final ASN1ObjectIdentifier id_dsa_with_sha3_256;
    public static final ASN1ObjectIdentifier id_dsa_with_sha3_384;
    public static final ASN1ObjectIdentifier id_dsa_with_sha3_512;
    public static final ASN1ObjectIdentifier id_ecdsa_with_sha3_224;
    public static final ASN1ObjectIdentifier id_ecdsa_with_sha3_256;
    public static final ASN1ObjectIdentifier id_ecdsa_with_sha3_384;
    public static final ASN1ObjectIdentifier id_ecdsa_with_sha3_512;
    public static final ASN1ObjectIdentifier id_hmacWithSHA3_224;
    public static final ASN1ObjectIdentifier id_hmacWithSHA3_256;
    public static final ASN1ObjectIdentifier id_hmacWithSHA3_384;
    public static final ASN1ObjectIdentifier id_hmacWithSHA3_512;
    public static final ASN1ObjectIdentifier id_rsassa_pkcs1_v1_5_with_sha3_224;
    public static final ASN1ObjectIdentifier id_rsassa_pkcs1_v1_5_with_sha3_256;
    public static final ASN1ObjectIdentifier id_rsassa_pkcs1_v1_5_with_sha3_384;
    public static final ASN1ObjectIdentifier id_rsassa_pkcs1_v1_5_with_sha3_512;
    public static final ASN1ObjectIdentifier id_sha224;
    public static final ASN1ObjectIdentifier id_sha256;
    public static final ASN1ObjectIdentifier id_sha384;
    public static final ASN1ObjectIdentifier id_sha3_224;
    public static final ASN1ObjectIdentifier id_sha3_256;
    public static final ASN1ObjectIdentifier id_sha3_384;
    public static final ASN1ObjectIdentifier id_sha3_512;
    public static final ASN1ObjectIdentifier id_sha512;
    public static final ASN1ObjectIdentifier id_sha512_224;
    public static final ASN1ObjectIdentifier id_sha512_256;
    public static final ASN1ObjectIdentifier id_shake128;
    public static final ASN1ObjectIdentifier id_shake128_len;
    public static final ASN1ObjectIdentifier id_shake256;
    public static final ASN1ObjectIdentifier id_shake256_len;
    public static final ASN1ObjectIdentifier nistAlgorithm;
    public static final ASN1ObjectIdentifier sigAlgs;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("2.16.840.1.101.3.4");
        nistAlgorithm = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch = aSN1ObjectIdentifier.branch("2");
        hashAlgs = aSN1ObjectIdentifierBranch;
        id_sha256 = aSN1ObjectIdentifierBranch.branch("1");
        id_sha384 = hashAlgs.branch("2");
        id_sha512 = hashAlgs.branch("3");
        id_sha224 = hashAlgs.branch("4");
        id_sha512_224 = hashAlgs.branch("5");
        id_sha512_256 = hashAlgs.branch(Constants.VIA_SHARE_TYPE_INFO);
        id_sha3_224 = hashAlgs.branch("7");
        id_sha3_256 = hashAlgs.branch(Constants.VIA_SHARE_TYPE_PUBLISHVIDEO);
        id_sha3_384 = hashAlgs.branch(Constants.VIA_SHARE_TYPE_MINI_PROGRAM);
        id_sha3_512 = hashAlgs.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_QQ);
        id_shake128 = hashAlgs.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_QZONE);
        id_shake256 = hashAlgs.branch(Constants.VIA_REPORT_TYPE_SET_AVATAR);
        id_hmacWithSHA3_224 = hashAlgs.branch("13");
        id_hmacWithSHA3_256 = hashAlgs.branch(Constants.VIA_REPORT_TYPE_MAKE_FRIEND);
        id_hmacWithSHA3_384 = hashAlgs.branch(Constants.VIA_REPORT_TYPE_WPA_STATE);
        id_hmacWithSHA3_512 = hashAlgs.branch(Constants.VIA_REPORT_TYPE_START_WAP);
        id_shake128_len = hashAlgs.branch(Constants.VIA_REPORT_TYPE_START_GROUP);
        id_shake256_len = hashAlgs.branch("18");
        id_KmacWithSHAKE128 = hashAlgs.branch(Constants.VIA_ACT_TYPE_NINETEEN);
        id_KmacWithSHAKE256 = hashAlgs.branch(JsContactsMgr.PERMISSION_DENIED_ERROR);
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch2 = nistAlgorithm.branch("1");
        aes = aSN1ObjectIdentifierBranch2;
        id_aes128_ECB = aSN1ObjectIdentifierBranch2.branch("1");
        id_aes128_CBC = aes.branch("2");
        id_aes128_OFB = aes.branch("3");
        id_aes128_CFB = aes.branch("4");
        id_aes128_wrap = aes.branch("5");
        id_aes128_GCM = aes.branch(Constants.VIA_SHARE_TYPE_INFO);
        id_aes128_CCM = aes.branch("7");
        id_aes128_wrap_pad = aes.branch(Constants.VIA_SHARE_TYPE_PUBLISHVIDEO);
        id_aes192_ECB = aes.branch("21");
        id_aes192_CBC = aes.branch(Constants.VIA_REPORT_TYPE_DATALINE);
        id_aes192_OFB = aes.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_TROOPBAR);
        id_aes192_CFB = aes.branch(Constants.VIA_REPORT_TYPE_CHAT_AIO);
        id_aes192_wrap = aes.branch(Constants.VIA_REPORT_TYPE_CHAT_AUDIO);
        id_aes192_GCM = aes.branch(Constants.VIA_REPORT_TYPE_CHAT_VIDEO);
        id_aes192_CCM = aes.branch("27");
        id_aes192_wrap_pad = aes.branch(Constants.VIA_ACT_TYPE_TWENTY_EIGHT);
        id_aes256_ECB = aes.branch("41");
        id_aes256_CBC = aes.branch("42");
        id_aes256_OFB = aes.branch("43");
        id_aes256_CFB = aes.branch("44");
        id_aes256_wrap = aes.branch("45");
        id_aes256_GCM = aes.branch("46");
        id_aes256_CCM = aes.branch("47");
        id_aes256_wrap_pad = aes.branch("48");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch3 = nistAlgorithm.branch("3");
        sigAlgs = aSN1ObjectIdentifierBranch3;
        id_dsa_with_sha2 = aSN1ObjectIdentifierBranch3;
        dsa_with_sha224 = aSN1ObjectIdentifierBranch3.branch("1");
        dsa_with_sha256 = sigAlgs.branch("2");
        dsa_with_sha384 = sigAlgs.branch("3");
        dsa_with_sha512 = sigAlgs.branch("4");
        id_dsa_with_sha3_224 = sigAlgs.branch("5");
        id_dsa_with_sha3_256 = sigAlgs.branch(Constants.VIA_SHARE_TYPE_INFO);
        id_dsa_with_sha3_384 = sigAlgs.branch("7");
        id_dsa_with_sha3_512 = sigAlgs.branch(Constants.VIA_SHARE_TYPE_PUBLISHVIDEO);
        id_ecdsa_with_sha3_224 = sigAlgs.branch(Constants.VIA_SHARE_TYPE_MINI_PROGRAM);
        id_ecdsa_with_sha3_256 = sigAlgs.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_QQ);
        id_ecdsa_with_sha3_384 = sigAlgs.branch(Constants.VIA_REPORT_TYPE_SHARE_TO_QZONE);
        id_ecdsa_with_sha3_512 = sigAlgs.branch(Constants.VIA_REPORT_TYPE_SET_AVATAR);
        id_rsassa_pkcs1_v1_5_with_sha3_224 = sigAlgs.branch("13");
        id_rsassa_pkcs1_v1_5_with_sha3_256 = sigAlgs.branch(Constants.VIA_REPORT_TYPE_MAKE_FRIEND);
        id_rsassa_pkcs1_v1_5_with_sha3_384 = sigAlgs.branch(Constants.VIA_REPORT_TYPE_WPA_STATE);
        id_rsassa_pkcs1_v1_5_with_sha3_512 = sigAlgs.branch(Constants.VIA_REPORT_TYPE_START_WAP);
    }
}
