package supwisdom;

import com.facebook.imageutils.JfifUtil;
import com.google.zxing.oned.Code39Reader;
import com.sangfor.dx.io.IndexType;
import com.sangfor.dx.io.instructions.InstructionCodec;
import com.taobao.weex.common.Constants;
import com.taobao.weex.ui.view.gesture.WXGesture;
import com.tencent.ijk.media.player.IjkMediaPlayer;
import io.dcloud.feature.audio.recorder.RecorderTask;
import org.bouncycastle.crypto.engines.IDEAEngine;
import org.bouncycastle.pqc.crypto.qtesla.HashUtils;
import tv.cjump.jni.DeviceUtils;

/* JADX INFO: compiled from: Proguard */
/* JADX INFO: loaded from: classes2.dex */
public final class e31 {
    public static final a A;
    public static final a A0;
    public static final a A1;
    public static final a A2;
    public static final a B;
    public static final a B0;
    public static final a B1;
    public static final a B2;
    public static final a C;
    public static final a C0;
    public static final a C1;
    public static final a C2;
    public static final a D;
    public static final a D0;
    public static final a D1;
    public static final a D2;
    public static final a E;
    public static final a E0;
    public static final a E1;
    public static final a E2;
    public static final a F;
    public static final a F0;
    public static final a F1;
    public static final a F2;
    public static final a G;
    public static final a G0;
    public static final a G1;
    public static final a G2;
    public static final a H;
    public static final a H0;
    public static final a H1;
    public static final a H2;
    public static final a I;
    public static final a I0;
    public static final a I1;
    public static final a I2;
    public static final a J;
    public static final a J0;
    public static final a J1;
    public static final a J2;
    public static final a K;
    public static final a K0;
    public static final a K1;
    public static final a K2;
    public static final a L;
    public static final a L0;
    public static final a L1;
    public static final a L2;
    public static final a M;
    public static final a M0;
    public static final a M1;
    public static final a M2;
    public static final a N;
    public static final a N0;
    public static final a N1;
    public static final a N2;
    public static final a O;
    public static final a O0;
    public static final a O1;
    public static final a O2;
    public static final a P;
    public static final a P0;
    public static final a P1;
    public static final a P2;
    public static final a Q;
    public static final a Q0;
    public static final a Q1;
    public static final a Q2;
    public static final a R;
    public static final a R0;
    public static final a R1;
    public static final a R2;
    public static final a S;
    public static final a S0;
    public static final a S1;
    public static final a S2;
    public static final a T;
    public static final a T0;
    public static final a T1;
    public static final a T2;
    public static final a U;
    public static final a U0;
    public static final a U1;
    public static final a U2;
    public static final a V;
    public static final a V0;
    public static final a V1;
    public static final a V2;
    public static final a W;
    public static final a W0;
    public static final a W1;
    public static final a W2;
    public static final a X;
    public static final a X0;
    public static final a X1;
    public static final a X2;
    public static final a Y;
    public static final a Y0;
    public static final a Y1;
    public static final a Y2;
    public static final a Z;
    public static final a Z0;
    public static final a Z1;
    public static final a Z2;

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public static final a[] f7416a;
    public static final a a0;
    public static final a a1;
    public static final a a2;
    public static final a a3;
    public static final a b;
    public static final a b0;
    public static final a b1;
    public static final a b2;
    public static final a b3;
    public static final a c;
    public static final a c0;
    public static final a c1;
    public static final a c2;
    public static final a c3;
    public static final a d;
    public static final a d0;
    public static final a d1;
    public static final a d2;
    public static final a d3;

    /* JADX INFO: renamed from: e, reason: collision with root package name */
    public static final a f7417e;
    public static final a e0;
    public static final a e1;
    public static final a e2;
    public static final a e3;
    public static final a f;
    public static final a f0;
    public static final a f1;
    public static final a f2;
    public static final a f3;
    public static final a g;
    public static final a g0;
    public static final a g1;
    public static final a g2;
    public static final a g3;
    public static final a h;
    public static final a h0;
    public static final a h1;
    public static final a h2;
    public static final a h3;
    public static final a i;
    public static final a i0;
    public static final a i1;
    public static final a i2;
    public static final a i3;
    public static final a j;
    public static final a j0;
    public static final a j1;
    public static final a j2;
    public static final a j3;
    public static final a k;
    public static final a k0;
    public static final a k1;
    public static final a k2;
    public static final a k3;
    public static final a l;
    public static final a l0;
    public static final a l1;
    public static final a l2;
    public static final a l3;
    public static final a m;
    public static final a m0;
    public static final a m1;
    public static final a m2;
    public static final a m3;
    public static final a n;
    public static final a n0;
    public static final a n1;
    public static final a n2;
    public static final a n3;
    public static final a o;
    public static final a o0;
    public static final a o1;
    public static final a o2;
    public static final a o3;
    public static final a p;
    public static final a p0;
    public static final a p1;
    public static final a p2;
    public static final a p3;
    public static final a q;
    public static final a q0;
    public static final a q1;
    public static final a q2;
    public static final a q3;
    public static final a r;
    public static final a r0;
    public static final a r1;
    public static final a r2;
    public static final a r3;
    public static final a s;
    public static final a s0;
    public static final a s1;
    public static final a s2;
    public static final a s3;
    public static final a t;
    public static final a t0;
    public static final a t1;
    public static final a t2;
    public static final a t3;
    public static final a u;
    public static final a u0;
    public static final a u1;
    public static final a u2;
    public static final a u3;
    public static final a v;
    public static final a v0;
    public static final a v1;
    public static final a v2;
    public static final a w;
    public static final a w0;
    public static final a w1;
    public static final a w2;
    public static final a x;
    public static final a x0;
    public static final a x1;
    public static final a x2;
    public static final a y;
    public static final a y0;
    public static final a y1;
    public static final a y2;
    public static final a z;
    public static final a z0;
    public static final a z1;
    public static final a z2;

    /* JADX INFO: compiled from: Proguard */
    public static class a {

        /* JADX INFO: renamed from: a, reason: collision with root package name */
        public final int f7418a;
        public final String b;
        public final IndexType c;

        public a(int i, String str, InstructionCodec instructionCodec, IndexType indexType) {
            this.f7418a = i;
            this.b = str;
            this.c = indexType;
        }

        public IndexType a() {
            return this.c;
        }

        public String b() {
            return this.b;
        }

        public int c() {
            return this.f7418a;
        }
    }

    static {
        InstructionCodec instructionCodec = InstructionCodec.FORMAT_00X;
        IndexType indexType = IndexType.NONE;
        b = new a(-1, "<special>", instructionCodec, indexType);
        c = new a(256, "packed-switch-payload", InstructionCodec.FORMAT_PACKED_SWITCH_PAYLOAD, indexType);
        d = new a(512, "sparse-switch-payload", InstructionCodec.FORMAT_SPARSE_SWITCH_PAYLOAD, indexType);
        f7417e = new a(768, "fill-array-data-payload", InstructionCodec.FORMAT_FILL_ARRAY_DATA_PAYLOAD, indexType);
        InstructionCodec instructionCodec2 = InstructionCodec.FORMAT_10X;
        f = new a(0, "nop", instructionCodec2, indexType);
        InstructionCodec instructionCodec3 = InstructionCodec.FORMAT_12X;
        g = new a(1, WXGesture.MOVE, instructionCodec3, indexType);
        InstructionCodec instructionCodec4 = InstructionCodec.FORMAT_22X;
        h = new a(2, "move/from16", instructionCodec4, indexType);
        InstructionCodec instructionCodec5 = InstructionCodec.FORMAT_32X;
        i = new a(3, "move/16", instructionCodec5, indexType);
        j = new a(4, "move-wide", instructionCodec3, indexType);
        k = new a(5, "move-wide/from16", instructionCodec4, indexType);
        l = new a(6, "move-wide/16", instructionCodec5, indexType);
        m = new a(7, "move-object", instructionCodec3, indexType);
        n = new a(8, "move-object/from16", instructionCodec4, indexType);
        o = new a(9, "move-object/16", instructionCodec5, indexType);
        InstructionCodec instructionCodec6 = InstructionCodec.FORMAT_11X;
        p = new a(10, "move-result", instructionCodec6, indexType);
        q = new a(11, "move-result-wide", instructionCodec6, indexType);
        r = new a(12, "move-result-object", instructionCodec6, indexType);
        s = new a(13, "move-exception", instructionCodec6, indexType);
        t = new a(14, "return-void", instructionCodec2, indexType);
        u = new a(15, Constants.Event.RETURN, instructionCodec6, indexType);
        v = new a(16, "return-wide", instructionCodec6, indexType);
        w = new a(17, "return-object", instructionCodec6, indexType);
        x = new a(18, "const/4", InstructionCodec.FORMAT_11N, indexType);
        InstructionCodec instructionCodec7 = InstructionCodec.FORMAT_21S;
        y = new a(19, "const/16", instructionCodec7, indexType);
        InstructionCodec instructionCodec8 = InstructionCodec.FORMAT_31I;
        z = new a(20, "const", instructionCodec8, indexType);
        InstructionCodec instructionCodec9 = InstructionCodec.FORMAT_21H;
        A = new a(21, "const/high16", instructionCodec9, indexType);
        B = new a(22, "const-wide/16", instructionCodec7, indexType);
        C = new a(23, "const-wide/32", instructionCodec8, indexType);
        D = new a(24, "const-wide", InstructionCodec.FORMAT_51L, indexType);
        E = new a(25, "const-wide/high16", instructionCodec9, indexType);
        InstructionCodec instructionCodec10 = InstructionCodec.FORMAT_21C;
        IndexType indexType2 = IndexType.STRING_REF;
        F = new a(26, "const-string", instructionCodec10, indexType2);
        G = new a(27, "const-string/jumbo", InstructionCodec.FORMAT_31C, indexType2);
        IndexType indexType3 = IndexType.TYPE_REF;
        H = new a(28, "const-class", instructionCodec10, indexType3);
        IndexType indexType4 = IndexType.NONE;
        I = new a(29, "monitor-enter", instructionCodec6, indexType4);
        J = new a(30, "monitor-exit", instructionCodec6, indexType4);
        K = new a(31, "check-cast", instructionCodec10, indexType3);
        InstructionCodec instructionCodec11 = InstructionCodec.FORMAT_22C;
        L = new a(32, "instance-of", instructionCodec11, indexType3);
        M = new a(33, "array-length", instructionCodec3, indexType4);
        N = new a(34, "new-instance", instructionCodec10, indexType3);
        O = new a(35, "new-array", instructionCodec11, indexType3);
        P = new a(36, "filled-new-array", InstructionCodec.FORMAT_35C, indexType3);
        Q = new a(37, "filled-new-array/range", InstructionCodec.FORMAT_3RC, indexType3);
        InstructionCodec instructionCodec12 = InstructionCodec.FORMAT_31T;
        R = new a(38, "fill-array-data", instructionCodec12, indexType4);
        S = new a(39, "throw", instructionCodec6, indexType4);
        T = new a(40, com.igexin.push.core.b.s, InstructionCodec.FORMAT_10T, indexType4);
        U = new a(41, "goto/16", InstructionCodec.FORMAT_20T, indexType4);
        V = new a(42, "goto/32", InstructionCodec.FORMAT_30T, indexType4);
        W = new a(43, "packed-switch", instructionCodec12, indexType4);
        X = new a(44, "sparse-switch", instructionCodec12, indexType4);
        InstructionCodec instructionCodec13 = InstructionCodec.FORMAT_23X;
        Y = new a(45, "cmpl-float", instructionCodec13, indexType4);
        Z = new a(46, "cmpg-float", instructionCodec13, indexType4);
        a0 = new a(47, "cmpl-double", instructionCodec13, indexType4);
        b0 = new a(48, "cmpg-double", instructionCodec13, indexType4);
        c0 = new a(49, "cmp-long", instructionCodec13, indexType4);
        InstructionCodec instructionCodec14 = InstructionCodec.FORMAT_22T;
        d0 = new a(50, "if-eq", instructionCodec14, indexType4);
        e0 = new a(51, "if-ne", instructionCodec14, indexType4);
        f0 = new a(52, "if-lt", instructionCodec14, indexType4);
        g0 = new a(53, "if-ge", instructionCodec14, indexType4);
        h0 = new a(54, "if-gt", instructionCodec14, indexType4);
        i0 = new a(55, "if-le", instructionCodec14, indexType4);
        InstructionCodec instructionCodec15 = InstructionCodec.FORMAT_21T;
        j0 = new a(56, "if-eqz", instructionCodec15, indexType4);
        k0 = new a(57, "if-nez", instructionCodec15, indexType4);
        l0 = new a(58, "if-ltz", instructionCodec15, indexType4);
        m0 = new a(59, "if-gez", instructionCodec15, indexType4);
        n0 = new a(60, "if-gtz", instructionCodec15, indexType4);
        o0 = new a(61, "if-lez", instructionCodec15, indexType4);
        p0 = new a(68, "aget", instructionCodec13, indexType4);
        q0 = new a(69, "aget-wide", instructionCodec13, indexType4);
        r0 = new a(70, "aget-object", instructionCodec13, indexType4);
        s0 = new a(71, "aget-boolean", instructionCodec13, indexType4);
        t0 = new a(72, "aget-byte", instructionCodec13, indexType4);
        u0 = new a(73, "aget-char", instructionCodec13, indexType4);
        v0 = new a(74, "aget-short", instructionCodec13, indexType4);
        IndexType indexType5 = IndexType.NONE;
        w0 = new a(75, "aput", instructionCodec13, indexType5);
        x0 = new a(76, "aput-wide", instructionCodec13, indexType5);
        y0 = new a(77, "aput-object", instructionCodec13, indexType5);
        z0 = new a(78, "aput-boolean", instructionCodec13, indexType5);
        A0 = new a(79, "aput-byte", instructionCodec13, indexType5);
        B0 = new a(80, "aput-char", instructionCodec13, indexType5);
        C0 = new a(81, "aput-short", instructionCodec13, indexType5);
        InstructionCodec instructionCodec16 = InstructionCodec.FORMAT_22C;
        IndexType indexType6 = IndexType.FIELD_REF;
        D0 = new a(82, "iget", instructionCodec16, indexType6);
        E0 = new a(83, "iget-wide", instructionCodec16, indexType6);
        F0 = new a(84, "iget-object", instructionCodec16, indexType6);
        G0 = new a(85, "iget-boolean", instructionCodec16, indexType6);
        H0 = new a(86, "iget-byte", instructionCodec16, indexType6);
        I0 = new a(87, "iget-char", instructionCodec16, indexType6);
        J0 = new a(88, "iget-short", instructionCodec16, indexType6);
        K0 = new a(89, "iput", instructionCodec16, indexType6);
        L0 = new a(90, "iput-wide", instructionCodec16, indexType6);
        M0 = new a(91, "iput-object", instructionCodec16, indexType6);
        N0 = new a(92, "iput-boolean", instructionCodec16, indexType6);
        O0 = new a(93, "iput-byte", instructionCodec16, indexType6);
        P0 = new a(94, "iput-char", instructionCodec16, indexType6);
        Q0 = new a(95, "iput-short", instructionCodec16, indexType6);
        InstructionCodec instructionCodec17 = InstructionCodec.FORMAT_21C;
        R0 = new a(96, "sget", instructionCodec17, indexType6);
        S0 = new a(97, "sget-wide", instructionCodec17, indexType6);
        T0 = new a(98, "sget-object", instructionCodec17, indexType6);
        U0 = new a(99, "sget-boolean", instructionCodec17, indexType6);
        V0 = new a(100, "sget-byte", instructionCodec17, indexType6);
        W0 = new a(101, "sget-char", instructionCodec17, indexType6);
        X0 = new a(102, "sget-short", instructionCodec17, indexType6);
        Y0 = new a(103, "sput", instructionCodec17, indexType6);
        Z0 = new a(104, "sput-wide", instructionCodec17, indexType6);
        a1 = new a(105, "sput-object", instructionCodec17, indexType6);
        b1 = new a(106, "sput-boolean", instructionCodec17, indexType6);
        c1 = new a(107, "sput-byte", instructionCodec17, indexType6);
        d1 = new a(108, "sput-char", instructionCodec17, indexType6);
        e1 = new a(109, "sput-short", instructionCodec17, indexType6);
        InstructionCodec instructionCodec18 = InstructionCodec.FORMAT_35C;
        IndexType indexType7 = IndexType.METHOD_REF;
        f1 = new a(110, "invoke-virtual", instructionCodec18, indexType7);
        g1 = new a(111, "invoke-super", instructionCodec18, indexType7);
        h1 = new a(112, "invoke-direct", instructionCodec18, indexType7);
        i1 = new a(113, "invoke-static", instructionCodec18, indexType7);
        j1 = new a(114, "invoke-interface", instructionCodec18, indexType7);
        InstructionCodec instructionCodec19 = InstructionCodec.FORMAT_3RC;
        k1 = new a(116, "invoke-virtual/range", instructionCodec19, indexType7);
        l1 = new a(117, "invoke-super/range", instructionCodec19, indexType7);
        m1 = new a(118, "invoke-direct/range", instructionCodec19, indexType7);
        n1 = new a(119, "invoke-static/range", instructionCodec19, indexType7);
        o1 = new a(120, "invoke-interface/range", instructionCodec19, indexType7);
        InstructionCodec instructionCodec20 = InstructionCodec.FORMAT_12X;
        IndexType indexType8 = IndexType.NONE;
        p1 = new a(123, "neg-int", instructionCodec20, indexType8);
        q1 = new a(124, "not-int", instructionCodec20, indexType8);
        r1 = new a(125, "neg-long", instructionCodec20, indexType8);
        s1 = new a(126, "not-long", instructionCodec20, indexType8);
        t1 = new a(127, "neg-float", instructionCodec20, indexType8);
        u1 = new a(128, "neg-double", instructionCodec20, indexType8);
        v1 = new a(129, "int-to-long", instructionCodec20, indexType8);
        w1 = new a(130, "int-to-float", instructionCodec20, indexType8);
        x1 = new a(com.igexin.push.core.a.c.h.b, "int-to-double", instructionCodec20, indexType8);
        y1 = new a(132, "long-to-int", instructionCodec20, indexType8);
        z1 = new a(133, "long-to-float", instructionCodec20, indexType8);
        A1 = new a(134, "long-to-double", instructionCodec20, indexType8);
        B1 = new a(135, "float-to-int", instructionCodec20, indexType8);
        C1 = new a(HashUtils.SECURE_HASH_ALGORITHM_KECCAK_256_RATE, "float-to-long", instructionCodec20, indexType8);
        D1 = new a(137, "float-to-double", instructionCodec20, indexType8);
        E1 = new a(138, "double-to-int", instructionCodec20, indexType8);
        F1 = new a(139, "double-to-long", instructionCodec20, indexType8);
        G1 = new a(140, "double-to-float", instructionCodec20, indexType8);
        H1 = new a(141, "int-to-byte", instructionCodec20, indexType8);
        I1 = new a(142, "int-to-char", instructionCodec20, indexType8);
        J1 = new a(143, "int-to-short", instructionCodec20, indexType8);
        InstructionCodec instructionCodec21 = InstructionCodec.FORMAT_23X;
        K1 = new a(144, "add-int", instructionCodec21, indexType8);
        L1 = new a(com.igexin.push.config.c.G, "sub-int", instructionCodec21, indexType8);
        M1 = new a(146, "mul-int", instructionCodec21, indexType8);
        N1 = new a(147, "div-int", instructionCodec21, indexType8);
        O1 = new a(Code39Reader.ASTERISK_ENCODING, "rem-int", instructionCodec21, indexType8);
        P1 = new a(149, "and-int", instructionCodec21, indexType8);
        Q1 = new a(150, "or-int", instructionCodec21, indexType8);
        R1 = new a(151, "xor-int", instructionCodec21, indexType8);
        S1 = new a(152, "shl-int", instructionCodec21, indexType8);
        T1 = new a(153, "shr-int", instructionCodec21, indexType8);
        U1 = new a(154, "ushr-int", instructionCodec21, indexType8);
        V1 = new a(155, "add-long", instructionCodec21, indexType8);
        W1 = new a(156, "sub-long", instructionCodec21, indexType8);
        X1 = new a(157, "mul-long", instructionCodec21, indexType8);
        Y1 = new a(158, "div-long", instructionCodec21, indexType8);
        Z1 = new a(159, "rem-long", instructionCodec21, indexType8);
        a2 = new a(160, "and-long", instructionCodec21, indexType8);
        b2 = new a(161, "or-long", instructionCodec21, indexType8);
        c2 = new a(162, "xor-long", instructionCodec21, indexType8);
        d2 = new a(163, "shl-long", instructionCodec21, indexType8);
        e2 = new a(164, "shr-long", instructionCodec21, indexType8);
        f2 = new a(165, "ushr-long", instructionCodec21, indexType8);
        g2 = new a(166, "add-float", instructionCodec21, indexType8);
        h2 = new a(167, "sub-float", instructionCodec21, indexType8);
        i2 = new a(HashUtils.SECURE_HASH_ALGORITHM_KECCAK_128_RATE, "mul-float", instructionCodec21, indexType8);
        j2 = new a(169, "div-float", instructionCodec21, indexType8);
        k2 = new a(170, "rem-float", instructionCodec21, indexType8);
        l2 = new a(171, "add-double", instructionCodec21, indexType8);
        IndexType indexType9 = IndexType.NONE;
        m2 = new a(172, "sub-double", instructionCodec21, indexType9);
        n2 = new a(173, "mul-double", instructionCodec21, indexType9);
        o2 = new a(174, "div-double", instructionCodec21, indexType9);
        p2 = new a(175, "rem-double", instructionCodec21, indexType9);
        InstructionCodec instructionCodec22 = InstructionCodec.FORMAT_12X;
        q2 = new a(176, "add-int/2addr", instructionCodec22, indexType9);
        r2 = new a(177, "sub-int/2addr", instructionCodec22, indexType9);
        s2 = new a(178, "mul-int/2addr", instructionCodec22, indexType9);
        t2 = new a(179, "div-int/2addr", instructionCodec22, indexType9);
        u2 = new a(180, "rem-int/2addr", instructionCodec22, indexType9);
        v2 = new a(181, "and-int/2addr", instructionCodec22, indexType9);
        w2 = new a(182, "or-int/2addr", instructionCodec22, indexType9);
        x2 = new a(DeviceUtils.EM_AARCH64, "xor-int/2addr", instructionCodec22, indexType9);
        y2 = new a(184, "shl-int/2addr", instructionCodec22, indexType9);
        z2 = new a(185, "shr-int/2addr", instructionCodec22, indexType9);
        A2 = new a(186, "ushr-int/2addr", instructionCodec22, indexType9);
        B2 = new a(187, "add-long/2addr", instructionCodec22, indexType9);
        C2 = new a(188, "sub-long/2addr", instructionCodec22, indexType9);
        D2 = new a(189, "mul-long/2addr", instructionCodec22, indexType9);
        E2 = new a(190, "div-long/2addr", instructionCodec22, indexType9);
        F2 = new a(191, "rem-long/2addr", instructionCodec22, indexType9);
        G2 = new a(192, "and-long/2addr", instructionCodec22, indexType9);
        H2 = new a(193, "or-long/2addr", instructionCodec22, indexType9);
        I2 = new a(194, "xor-long/2addr", instructionCodec22, indexType9);
        J2 = new a(195, "shl-long/2addr", instructionCodec22, indexType9);
        K2 = new a(196, "shr-long/2addr", instructionCodec22, indexType9);
        L2 = new a(197, "ushr-long/2addr", instructionCodec22, indexType9);
        M2 = new a(198, "add-float/2addr", instructionCodec22, indexType9);
        N2 = new a(199, "sub-float/2addr", instructionCodec22, indexType9);
        O2 = new a(200, "mul-float/2addr", instructionCodec22, indexType9);
        P2 = new a(201, "div-float/2addr", instructionCodec22, indexType9);
        Q2 = new a(202, "rem-float/2addr", instructionCodec22, indexType9);
        R2 = new a(203, "add-double/2addr", instructionCodec22, indexType9);
        S2 = new a(204, "sub-double/2addr", instructionCodec22, indexType9);
        T2 = new a(205, "mul-double/2addr", instructionCodec22, indexType9);
        U2 = new a(206, "div-double/2addr", instructionCodec22, indexType9);
        V2 = new a(207, "rem-double/2addr", instructionCodec22, indexType9);
        InstructionCodec instructionCodec23 = InstructionCodec.FORMAT_22S;
        W2 = new a(JfifUtil.MARKER_RST0, "add-int/lit16", instructionCodec23, indexType9);
        X2 = new a(209, "rsub-int", instructionCodec23, indexType9);
        Y2 = new a(IjkMediaPlayer.MEDIA_HLS_KEY_ERROR, "mul-int/lit16", instructionCodec23, indexType9);
        Z2 = new a(211, "div-int/lit16", instructionCodec23, indexType9);
        a3 = new a(IjkMediaPlayer.MEDIA_VIDEO_DECODER_ERROR, "rem-int/lit16", instructionCodec23, indexType9);
        b3 = new a(213, "and-int/lit16", instructionCodec23, indexType9);
        c3 = new a(214, "or-int/lit16", instructionCodec23, indexType9);
        d3 = new a(JfifUtil.MARKER_RST7, "xor-int/lit16", instructionCodec23, indexType9);
        InstructionCodec instructionCodec24 = InstructionCodec.FORMAT_22B;
        e3 = new a(JfifUtil.MARKER_SOI, "add-int/lit8", instructionCodec24, indexType9);
        f3 = new a(217, "rsub-int/lit8", instructionCodec24, indexType9);
        g3 = new a(218, "mul-int/lit8", instructionCodec24, indexType9);
        IndexType indexType10 = IndexType.NONE;
        h3 = new a(219, "div-int/lit8", instructionCodec24, indexType10);
        i3 = new a(RecorderTask.FRAME_COUNT, "rem-int/lit8", instructionCodec24, indexType10);
        j3 = new a(221, "and-int/lit8", instructionCodec24, indexType10);
        k3 = new a(222, "or-int/lit8", instructionCodec24, indexType10);
        l3 = new a(223, "xor-int/lit8", instructionCodec24, indexType10);
        m3 = new a(224, "shl-int/lit8", instructionCodec24, indexType10);
        n3 = new a(225, "shr-int/lit8", instructionCodec24, indexType10);
        o3 = new a(226, "ushr-int/lit8", instructionCodec24, indexType10);
        InstructionCodec instructionCodec25 = InstructionCodec.FORMAT_45CC;
        IndexType indexType11 = IndexType.METHOD_AND_PROTO_REF;
        p3 = new a(250, "invoke-polymorphic", instructionCodec25, indexType11);
        q3 = new a(251, "invoke-polymorphic/range", InstructionCodec.FORMAT_4RCC, indexType11);
        InstructionCodec instructionCodec26 = InstructionCodec.FORMAT_35C;
        IndexType indexType12 = IndexType.CALL_SITE_REF;
        r3 = new a(252, "invoke-custom", instructionCodec26, indexType12);
        s3 = new a(com.igexin.push.config.c.E, "invoke-custom/range", InstructionCodec.FORMAT_3RC, indexType12);
        InstructionCodec instructionCodec27 = InstructionCodec.FORMAT_21C;
        t3 = new a(254, "const-method-handle", instructionCodec27, IndexType.METHOD_HANDLE_REF);
        u3 = new a(255, "const-method-type", instructionCodec27, IndexType.PROTO_REF);
        f7416a = new a[IDEAEngine.BASE];
        a(b);
        a(c);
        a(d);
        a(f7417e);
        a(f);
        a(g);
        a(h);
        a(i);
        a(j);
        a(k);
        a(l);
        a(m);
        a(n);
        a(o);
        a(p);
        a(q);
        a(r);
        a(s);
        a(t);
        a(u);
        a(v);
        a(w);
        a(x);
        a(y);
        a(z);
        a(A);
        a(B);
        a(C);
        a(D);
        a(E);
        a(F);
        a(G);
        a(H);
        a(I);
        a(J);
        a(K);
        a(L);
        a(M);
        a(N);
        a(O);
        a(P);
        a(Q);
        a(R);
        a(S);
        a(T);
        a(U);
        a(V);
        a(W);
        a(X);
        a(Y);
        a(Z);
        a(a0);
        a(b0);
        a(c0);
        a(d0);
        a(e0);
        a(f0);
        a(g0);
        a(h0);
        a(i0);
        a(j0);
        a(k0);
        a(l0);
        a(m0);
        a(n0);
        a(o0);
        a(p0);
        a(q0);
        a(r0);
        a(s0);
        a(t0);
        a(u0);
        a(v0);
        a(w0);
        a(x0);
        a(y0);
        a(z0);
        a(A0);
        a(B0);
        a(C0);
        a(D0);
        a(E0);
        a(F0);
        a(G0);
        a(H0);
        a(I0);
        a(J0);
        a(K0);
        a(L0);
        a(M0);
        a(N0);
        a(O0);
        a(P0);
        a(Q0);
        a(R0);
        a(S0);
        a(T0);
        a(U0);
        a(V0);
        a(W0);
        a(X0);
        a(Y0);
        a(Z0);
        a(a1);
        a(b1);
        a(c1);
        a(d1);
        a(e1);
        a(f1);
        a(g1);
        a(h1);
        a(i1);
        a(j1);
        a(k1);
        a(l1);
        a(m1);
        a(n1);
        a(o1);
        a(p1);
        a(q1);
        a(r1);
        a(s1);
        a(t1);
        a(u1);
        a(v1);
        a(w1);
        a(x1);
        a(y1);
        a(z1);
        a(A1);
        a(B1);
        a(C1);
        a(D1);
        a(E1);
        a(F1);
        a(G1);
        a(H1);
        a(I1);
        a(J1);
        a(K1);
        a(L1);
        a(M1);
        a(N1);
        a(O1);
        a(P1);
        a(Q1);
        a(R1);
        a(S1);
        a(T1);
        a(U1);
        a(V1);
        a(W1);
        a(X1);
        a(Y1);
        a(Z1);
        a(a2);
        a(b2);
        a(c2);
        a(d2);
        a(e2);
        a(f2);
        a(g2);
        a(h2);
        a(i2);
        a(j2);
        a(k2);
        a(l2);
        a(m2);
        a(n2);
        a(o2);
        a(p2);
        a(q2);
        a(r2);
        a(s2);
        a(t2);
        a(u2);
        a(v2);
        a(w2);
        a(x2);
        a(y2);
        a(z2);
        a(A2);
        a(B2);
        a(C2);
        a(D2);
        a(E2);
        a(F2);
        a(G2);
        a(H2);
        a(I2);
        a(J2);
        a(K2);
        a(L2);
        a(M2);
        a(N2);
        a(O2);
        a(P2);
        a(Q2);
        a(R2);
        a(S2);
        a(T2);
        a(U2);
        a(V2);
        a(W2);
        a(X2);
        a(Y2);
        a(Z2);
        a(a3);
        a(b3);
        a(c3);
        a(d3);
        a(e3);
        a(f3);
        a(g3);
        a(h3);
        a(i3);
        a(j3);
        a(k3);
        a(l3);
        a(m3);
        a(n3);
        a(o3);
        a(p3);
        a(q3);
        a(r3);
        a(s3);
        a(t3);
        a(u3);
    }

    public static a a(int i4) {
        try {
            a aVar = f7416a[i4 + 1];
            if (aVar != null) {
                return aVar;
            }
        } catch (ArrayIndexOutOfBoundsException unused) {
        }
        throw new IllegalArgumentException("bogus opcode: " + m61.e(i4));
    }

    public static IndexType b(int i4) {
        return a(i4).a();
    }

    public static String c(int i4) {
        return a(i4).b();
    }

    public static void a(a aVar) {
        f7416a[aVar.c() + 1] = aVar;
    }
}
