package supwisdom;

import android.graphics.Color;
import io.dcloud.feature.audio.recorder.RecorderTask;
import java.io.File;
import java.util.Map;
import org.bouncycastle.pqc.crypto.qtesla.HashUtils;

/* JADX INFO: compiled from: Proguard */
/* JADX INFO: loaded from: classes2.dex */
public class i71 {

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public static int f7920a = 300;
    public static a b = new a();

    /* JADX INFO: compiled from: Proguard */
    public static class a {
        public String A;
        public String A0;
        public String A1;
        public String A2;
        public String A3;
        public String A4;
        public String B;
        public String B0;
        public String B1;
        public String B2;
        public String B3;
        public String B4;
        public String C;
        public String C0;
        public String C1;
        public String C2;
        public String C3;
        public String C4;
        public String D;
        public String D0;
        public String D1;
        public String D2;
        public String D3;
        public String D4;
        public String E;
        public String E0;
        public String E1;
        public String E2;
        public String E3;
        public String E4;
        public String F;
        public String F0;
        public String F1;
        public String F2;
        public String F3;
        public String F4;
        public String G;
        public String G0;
        public String G1;
        public String G2;
        public String G3;
        public String G4;
        public String H;
        public String H0;
        public String H1;
        public String H2;
        public String H3;
        public String H4;
        public String I;
        public String I0;
        public String I1;
        public String I2;
        public String I3;
        public String I4;
        public String J;
        public String J0;
        public String J1;
        public String J2;
        public String J3;
        public String J4;
        public String K;
        public String K0;
        public String K1;
        public String K2;
        public String K3;
        public String K4;
        public String L;
        public String L0;
        public String L1;
        public String L2;
        public String L3;
        public String L4;
        public String M;
        public String M0;
        public String M1;
        public String M2;
        public String M3;
        public String M4;
        public String N;
        public String N0;
        public String N1;
        public String N2;
        public String N3;
        public String N4;
        public String O;
        public String O0;
        public String O1;
        public String O2;
        public String O3;
        public String O4;
        public String P;
        public String P0;
        public String P1;
        public String P2;
        public String P3;
        public String P4;
        public String Q;
        public String Q0;
        public String Q1;
        public String Q2;
        public String Q3;
        public String Q4;
        public String R;
        public String R0;
        public String R1;
        public String R2;
        public String R3;
        public String S;
        public String S0;
        public String S1;
        public String S2;
        public String S3;
        public String T;
        public String T0;
        public String T1;
        public String T2;
        public String T3;
        public String U;
        public String U0;
        public String U1;
        public String U2;
        public String U3;
        public String V;
        public String V0;
        public String V1;
        public String V2;
        public String V3;
        public String W;
        public String W0;
        public String W1;
        public String W2;
        public String W3;
        public String X;
        public String X0;
        public String X1;
        public String[] X2;
        public String X3;
        public String Y;
        public String Y0;
        public String Y1;
        public String[] Y2;
        public String Y3;
        public String Z;
        public String Z0;
        public String Z1;
        public String Z2;
        public String Z3;

        /* JADX INFO: renamed from: a, reason: collision with root package name */
        public String f7921a;
        public String a0;
        public String a1;
        public String a2;
        public String a3;
        public String a4;
        public String b;
        public String b0;
        public String b1;
        public String b2;
        public String b3;
        public String b4;
        public String c;
        public String c0;
        public String c1;
        public String c2;
        public String c3;
        public String c4;
        public String d;
        public String d0;
        public String d1;
        public String d2;
        public String d3;
        public String d4;

        /* JADX INFO: renamed from: e, reason: collision with root package name */
        public String f7922e;
        public String e0;
        public String e1;
        public String e2;
        public String e3;
        public String e4;
        public String f;
        public String f0;
        public String f1;
        public String f2;
        public String f3;
        public String f4;
        public String g;
        public String g0;
        public String g1;
        public Map<String, String> g2;
        public String g3;
        public String g4;
        public String h;
        public String h0;
        public String h1;
        public String h2;
        public String h3;
        public String h4;
        public String i;
        public String i0;
        public String i1;
        public String i2;
        public String i3;
        public String i4;
        public String j;
        public String j0;
        public String j1;
        public String j2;
        public String j3;
        public String j4;
        public String k;
        public String k0;
        public String k1;
        public String k2;
        public String k3;
        public String k4;
        public String l;
        public String l0;
        public String l1;
        public String l2;
        public String l3;
        public String l4;
        public String m;
        public String m0;
        public String m1;
        public String m2;
        public String m3;
        public String m4;
        public String n;
        public String n0;
        public String n1;
        public String n2;
        public String n3;
        public String n4;
        public String o;
        public String o0;
        public String o1;
        public String o2;
        public String o3;
        public String o4;
        public String p;
        public String p0;
        public String p1;
        public String p2;
        public String p3;
        public String p4;
        public String q;
        public String q0;
        public String q1;
        public String q2;
        public String q3;
        public String q4;
        public String r;
        public String r0;
        public String r1;
        public String r2;
        public String r3;
        public String r4;
        public String s;
        public String s0;
        public String s1;
        public String s2;
        public String s3;
        public String s4;
        public String t;
        public String t0;
        public String t1;
        public String t2;
        public String t3;
        public String t4;
        public String u;
        public String u0;
        public String u1;
        public String u2;
        public String u3;
        public String u4;
        public String v;
        public String v0;
        public String v1;
        public String v2;
        public String v3;
        public String v4;
        public String w;
        public String w0;
        public String w1;
        public String w2;
        public String w3;
        public String w4;
        public String x;
        public String x0;
        public String x1;
        public String x2;
        public String x3;
        public String x4;
        public String y;
        public String y0;
        public String y1;
        public String y2;
        public String y3;
        public String y4;
        public String z;
        public String z0;
        public String z1;
        public String z2;
        public String z3;
        public String z4;
    }

    /* JADX INFO: compiled from: Proguard */
    public static class b {

        /* JADX INFO: renamed from: a, reason: collision with root package name */
        public static final int f7923a;
        public static final int b;
        public static final int c;
        public static final int d;

        /* JADX INFO: renamed from: e, reason: collision with root package name */
        public static final int f7924e;
        public static final int f;
        public static final int g;
        public static final int h;
        public static final int i;
        public static final int j;
        public static final int k;
        public static final int l;
        public static final int m;
        public static final int n;
        public static final int o;
        public static final int p;
        public static final int q;
        public static final int r;
        public static final int s;
        public static final int t;
        public static final int u;

        static {
            Color.rgb(239, 239, 239);
            Color.rgb(200, 200, 200);
            Color.rgb(0, 122, 255);
            Color.rgb(139, 191, 252);
            Color.rgb(139, 191, 252);
            Color.rgb(217, 217, 217);
            Color.rgb(36, 172, 112);
            Color.argb(204, 20, 90, 60);
            Color.rgb(139, 191, 252);
            Color.rgb(36, 172, 112);
            Color.rgb(49, 185, 125);
            Color.rgb(246, 246, 246);
            Color.rgb(80, 160, 240);
            Color.rgb(40, 80, 160);
            Color.rgb(20, 40, 80);
            Color.rgb(80, 160, 240);
            Color.rgb(200, 200, 200);
            Color.rgb(80, 160, 240);
            Color.rgb(139, 191, 252);
            Color.rgb(RecorderTask.FRAME_COUNT, RecorderTask.FRAME_COUNT, RecorderTask.FRAME_COUNT);
            Color.rgb(255, 87, 87);
            Color.rgb(0, 150, HashUtils.SECURE_HASH_ALGORITHM_KECCAK_256_RATE);
            Color.rgb(26, 56, 78);
            Color.rgb(246, 246, 246);
            f7923a = Color.rgb(28, 110, 255);
            b = Color.rgb(254, 254, 254);
            c = Color.rgb(47, 53, 64);
            d = Color.rgb(111, 119, 133);
            f7924e = Color.rgb(230, 230, 230);
            Color.rgb(85, 85, 85);
            Color.rgb(102, 102, 102);
            f = Color.parseColor("#5C5C5C");
            g = Color.parseColor("#F7F9FC");
            h = Color.parseColor("#D8D8D8");
            i = Color.parseColor("#1C6EFF");
            j = Color.parseColor("#0D51D9");
            k = Color.parseColor("#EDF1F7");
            l = Color.parseColor("#BEC3CC");
            m = Color.parseColor("#E1E5EB");
            n = Color.parseColor("#2F3540");
            o = Color.parseColor("#D3D7DE");
            Color.parseColor("#EDF1F7");
            Color.parseColor("#F7F9FC");
            Color.parseColor("#C0CDE4");
            p = Color.parseColor("#1C6EFF");
            q = Color.parseColor("#A1A7B3");
            r = Color.parseColor("#C2C2C2");
            s = Color.parseColor("#1E232B");
            t = Color.rgb(225, 229, 235);
            u = Color.rgb(111, 119, 133);
            Color.parseColor("#A9A9A9");
            Color.parseColor("#E8F4FF");
            Color.parseColor("#F52727");
            Color.parseColor("#1C6EFF");
        }
    }

    /* JADX INFO: compiled from: Proguard */
    public static class c {

        /* JADX INFO: renamed from: a, reason: collision with root package name */
        public static final int f7925a = v71.a(4.0f);
        public static final int b;
        public static final int c;
        public static final int d;

        /* JADX INFO: renamed from: e, reason: collision with root package name */
        public static final int f7926e;
        public static final int f;
        public static final int g;
        public static final int h;
        public static final int i;
        public static final int j;
        public static final int k;
        public static final int l;
        public static final int m;
        public static final int n;
        public static final int o;
        public static final int p;
        public static final int q;
        public static final int r;
        public static final int s;
        public static final int t;
        public static final int u;
        public static final int v;
        public static final int w;
        public static final int x;
        public static final int y;
        public static final int z;

        static {
            v71.a(2.0f);
            v71.a(8.0f);
            b = v71.a(24.0f);
            c = v71.a(1.0f);
            d = v71.a(10.0f);
            f7926e = v71.a(16.0f);
            f = v71.a(10.0f);
            g = v71.a(16.0f);
            h = v71.a(24.0f);
            i = v71.a(32.0f);
            j = v71.a(48.0f);
            k = v71.a(46.0f);
            l = v71.a(65.0f);
            m = v71.a(40.0f);
            v71.a(22.0f);
            v71.a(65.0f);
            v71.a(33.0f);
            n = v71.a(48.0f);
            o = v71.a(12.0f);
            v71.a(156.0f);
            p = v71.a(64.0f);
            q = v71.a(5.0f);
            r = v71.a(100.0f);
            s = v71.a(19.0f);
            t = v71.a(120.0f);
            u = v71.a(6.0f);
            v = v71.a(12.0f);
            w = v71.a(44.0f);
            v71.a(60.0f);
            x = v71.a(16.0f);
            y = v71.a(10.0f);
            z = v71.a(10.0f);
            v71.a(44.0f);
            v71.a(10.0f);
            v71.a(20.0f);
            v71.a(30.0f);
            v71.a(10.0f);
            v71.a(40.0f);
            v71.a(10.0f);
            v71.a(6.0f);
            v71.a(10.0f);
            v71.a(10.0f);
            v71.a(15.0f);
            v71.a(170.0f);
            v71.a(10.0f);
            v71.a(10.0f);
            v71.a(4.0f);
            v71.a(4.0f);
            v71.a(10.0f);
            v71.a(10.0f);
            v71.a(326.0f);
            v71.a(230.0f);
            v71.a(30.0f);
            v71.a(21.0f);
            v71.a(3.0f);
            v71.a(45.0f);
            v71.a(16.0f);
            v71.a(10.0f);
            v71.a(2.0f);
            v71.a(25.0f);
            v71.a(40.0f);
            v71.a(64.0f);
            v71.a(14.0f);
            v71.a(17.0f);
            v71.a(5.0f);
            v71.a(16.0f);
            v71.a(5.0f);
            v71.a(7.0f);
            v71.a(20.0f);
            v71.a(10.0f);
            v71.a(24.0f);
        }
    }

    static {
        a();
        StringBuilder sb = new StringBuilder();
        sb.append("com_sangfor_easyapp_original");
        String str = File.separator;
        sb.append(str);
        sb.append("ori_apk_sign_cert");
        sb.toString();
        String str2 = "com_sangfor_easyapp_original" + str + com.igexin.push.core.b.Y;
    }

    public static void a() {
        h71.a();
    }
}
